[build]
  command = "npm install --legacy-peer-deps && npm run build && ls -la .next"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (you'll need to set these in Netlify dashboard)
# OPENAI_API_KEY = "your_openai_key_here"